### ISSUE TITLE
[Request] Lower AFK timeout value, starting from 1 minute

### ISSUE THREAD

**Issue by doom-hamster** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#50] opened 2023-08-07 09:08 UTC
Would be nice if there was a lower minimum value for Idle timeout timer, instead of **5 minutes** currently - could be from **1 minute**.

Also a numerical box to set the timeout value would be easier in my opinion (and more precise),  than the slider. A simple integer input, in minutes.

**Comment by RoguedBear** [comment] 2023-08-08 05:23
I have been getting this specific request multiple times (duplicate of #2).
Seeing this multiple times i am convinced i can complete this request in the middle ground.

I have given my reasoning why an afk time below 5 minutes does not make sense, as in it if you have not opened discord window in 5 minutes, it seems like a pretty good indicator that you're afk. 

However, there is a way for you to input a custom timeout value by editing the config file of the plugin. In the meanwhile i get time to add this feature in the plugin settings page, you can edit the configuration file directly to achieve a lower afk timeout.

my detailed response and the way to edit the timeout are written here: https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/issues/2#issuecomment-1024280678

**Closed** 2023-08-08 09:34 UTC
Labels: duplicate
