### ISSUE TITLE
"Object" Messing with code

### ISSUE THREAD

**Issue by Austinkid20** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#25] opened 2022-08-06 14:38 UTC
When opening discord an error for the plugin shows with the word "Object" being red.
![image_2022-08-06_073839884](https://user-images.githubusercontent.com/110731995/183253555-f36938c4-b18f-4c4f-ba15-84d17eda3e7e.png)

**Comment by Austinkid20** [comment] 2022-08-06 14:41
Saw in closed that other users were experiencing the same. So that's my bad with putting this issue out again.

**Comment by RoguedBear** [comment] 2022-08-06 15:55
you can download the github version if you don't want to wait for the update to be approved. 
wont be closing the issue for now.

duplicate of #24

**Comment by RoguedBear** [comment] 2022-08-06 16:23
you need to redownload the plugin.
BD doesnt show update banners for plugins with construction error. Since the betterdiscord site doesnt point to the latest version as of now, you'd have to download from the repository

**Closed by RoguedBear** 2022-08-06 16:23 UTC
Labels: duplicate
