### ISSUE TITLE
AutoidleOnAFK Won't Open, and gave me an error message

### ISSUE THREAD

**Issue by GrayV60** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#35] opened 2022-10-10 08:45 UTC
Not sure what to do about this, can someone please help?

`TypeError: Cannot read property 'StatusSetting' of undefined
    at plugin (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:67:49)
    at eval (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:292:13)
    at eval (betterdiscord://plugins/AutoIdleOnAFK.plugin.js:293:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)`

**Comment by RoguedBear** [comment] 2022-10-10 10:48
duplicate of #34.
Due to a recent discord update that broke majority of plugins, so did AutoIdleOnAFK. As far as I know, and have talked to people there doesn't seem to be a way to access the modules responsible to change the status. Atleast not yet.

so the plugin is gonna be broken for a while until a workaround or a way to access the module is found

**Closed by RoguedBear** 2022-10-10 10:48 UTC
