### ISSUE TITLE
most plugin setting options aren't visible anymore

### ISSUE THREAD

**Issue by thunderzip** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#37] opened 2022-11-25 00:31 UTC
The settings panel for this plugin lacks most of the settings when compared to the screenshot posted on the main github page for this plugin, or on the betterdiscord page for this plugin. I have attatched a screenshot of what I see below. When I installed this plugin, everything worked perfectly, but recently many of the settings seem to have disappeared. I have uninstalled and reinstalled it several times with no luck. Is this a common or fixable issue?
![image](https://user-images.githubusercontent.com/119019147/203878026-759ebb9a-ffa8-492b-a1b9-a89e51a3d9af.png)

**Comment by RoguedBear** [comment] 2022-11-26 21:09
oh no. this is also visible on my end too.
Something must have been changed in the meanwhile in Zlib, because when i made the new release a month back the settings page was completely visible.

I'll work on the issue when i get some time, in the meanwhile if you want to change some settings, you can do so by changing the respective config options in the BD plugin folder directory.
the file would be called `AutoIdleOnAFK.config.json`

thanks for letting me know

**Comment by RoguedBear** [comment] 2022-12-24 10:04
dropping an update that all settings seem to be visible again. Most probably an update on Zlib fixed it automatically.

Let me know if the issue is still persistent on your side, closing this issue for now

![image](https://user-images.githubusercontent.com/39442192/209431065-2fd26353-2895-49ac-bc84-c977e56d1afe.png)

**Closed by RoguedBear** 2022-12-24 10:04 UTC
Labels: bug
